# fly.toml app configuration file generated for auth-demo-spring on 2023-09-15T00:49:09-02:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "auth-demo-spring"
primary_region = "yul"

[build]
  dockerfile = "./Dockerfile"
  ignorefile = "./.dockerignore"

[env]
  SPRING_PROFILES_ACTIVE = "prod"
  HOST = "0.0.0.0"
  PORT = "8081"
  REDIS_HOST = "fly-auth-demo-express-redis.upstash.io"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
